added curio handler for easy identification of what curio is equipped
added network handler to seperate network code from main class

big code cleanup on all artifact classes

all artifacts tested and work as intended

weird unknown error when opening a world that might need fixing

attributes being applied twice on server side bug need to fix

error: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 17 column 2 path $.key.c.